/* config.h: configuration settings.
 *
 * This file is automatically generated by setup.py
 */

/* Define to 1 if iconv() should be used for converting character sets. */
#undef USE_ICONV

/* Define to 1 if you have the <sys/errno.h> header file. */
#define HAVE_SYS_ERRNO_H 1

/* Type used for input to iconv. */
#define ICONV_INPUT_TYPE char *

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* The name of this package. */
#define PACKAGE htmlparser
